In [1]:
import pandas as pd

df = pd.read_csv('train.csv')

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
import pandas as pd

df = pd.read_csv('train.csv')

print(df.head())

df.info()

df.drop(['Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

df['Age'] = df['Age'].fillna(df['Age'].median())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [3]:
import pandas as pd

df = pd.read_csv('train.csv')

print(df.head())

df.info()

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [2]:
import pandas as pd

df = pd.read_csv('train.csv')

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
import pandas as pd

df = pd.read_csv('train.csv')

df.head()

print(f"data format: {df.shape}")

df.info()

print(df.isnull().sum())

data format: (891, 12)
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
import pandas as pd

df = pd.read_csv('train.csv')

df.head()

print(f"data format: {df.shape}")

df.info()

print(df.isnull().sum())

df.drop(['Name', 'Ticket', 'Cabin'], axis=1, inplace=True) 

df['Age'] = df['Age'].fillna(df['Age'].median()) 

df.dropna(subset=['Embarked'], inplace=True)

print(df.isnull().sum())

data format: (891, 12)
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [5]:
import pandas as pd

df = pd.read_csv('train.csv')

df.head()

print(f"data format: {df.shape}")

df.info()

print(df.isnull().sum())

df.drop(['Name', 'Ticket', 'Cabin'], axis=1, inplace=True) 

df['Age'] = df['Age'].fillna(df['Age'].median()) 

df.dropna(subset=['Embarked'], inplace=True)

print(df.isnull().sum())

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1}) 

df = pd.get_dummies(df, columns=['Embarked']) 

print(df.dtypes)

data format: (891, 12)
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64
PassengerId      int64
Survived         int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked_C        bool
Embarked_Q        bool
Embarked_S        bool
dtype: object

In [6]:
import pandas as pd

df = pd.read_csv('train.csv')

df.head()

print(f"data format: {df.shape}")

df.info()

print(df.isnull().sum())

df.drop(['Name', 'Ticket', 'Cabin'], axis=1, inplace=True) 

df['Age'] = df['Age'].fillna(df['Age'].median()) 

df.dropna(subset=['Embarked'], inplace=True)

print(df.isnull().sum())

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1}) 

df = pd.get_dummies(df, columns=['Embarked']) 

print(df.dtypes)

y = df['Survived']

features = ['Pclass', 'Sex', 'Age', 'Fare']
X = df[features]

data format: (891, 12)
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64
PassengerId      int64
Survived         int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked_C        bool
Embarked_Q        bool
Embarked_S        bool
dtype: object

In [8]:
import pandas as pd

# 1. download and Load the dataset
# load the dataset from train.csv
df = pd.read_csv('train.csv')

# Create a DataFrame and Display the first rows
print("first rows of the dataset")
display(df.head())

# 2. explore the dataset
# determine number of rows and columns
print(f"\ndataset shape (rows, columns): {df.shape}")

# identify data types and presence of missing values 
print("\ndataset info & missing values")
df.info()
print(df.isnull().sum())

# identify numerical and categorical features
# numerical: PassengerId, Survived, Pclass, Age, SibSp, Parch, Fare
# categorical: Sex, Embarked, Name, Ticket, Cabin

# 3. data cleaning (Task B: Median)
# identify missing values before cleaning 
print(f"\nMissing Age values before: {df['Age'].isnull().sum()}")

# remove irrelevant columns: Name, Ticket, Cabin
df.drop(['Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

# Task B: fill missing values using median
df['Age'] = df['Age'].fillna(df['Age'].median())

# remove any remaining rows with missing values (e.g., Embarked)
df.dropna(subset=['Embarked'], inplace=True)

# verify that missing values are handled 
print(f"missing age values after: {df['Age'].isnull().sum()}")
print("\ntotal missing values in final dataset:", df.isnull().sum().sum())

# 4. data transformation
# convert categorical features (Sex, Embarked) into numerical format 
# Map Sex: male to 0, female to 1
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

# use One-Hot Encoding for Embarked to ensure only numerical values 
df = pd.get_dummies(df, columns=['Embarked'])

# 5. feature selection
# 5.1. Define the target variable (Survived) 
target = df['Survived']

# 5.2. select at least 4 features 
# chosen features: Pclass, Sex, Age, Fare
features = df[['Pclass', 'Sex', 'Age', 'Fare']]

# 5.3. justification:
# - Sex and Age: 'Women and children first' policy prioritized these groups.
# - Pclass and Fare: Represent socio-economic status and proximity to lifeboats.

# 6. Final Dataset
# ensure no missing values and all features are numerical 
print("\n Final Dataset Types")
print(features.dtypes)
print("\nFinal dataset is ready for model training.")

first rows of the dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

dataset shape (rows, columns): (891, 12)

dataset info & missing values
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Missing Age values before: 177
missing age values after: 0

total missing values in final dataset: 0

 Final Dataset Types
Pclass      int64
Sex         int64
Age       float64
Fare      float64
dtype: object

Final dataset is ready for model training.

In [11]:
In this assignment I completed the main steps of the machine learning workflow, including data loading, exploration, cleaning, transformation, and feature selection.

The most challenging part was handling missing values and deciding which columns to remove or keep.

I used median imputation for the Age column, removed irrelevant features, and converted categorical variables into numerical format.

The final dataset contains no missing values and only numerical features, so it is ready for machine learning model training.

SyntaxError: invalid syntax (2831528218.py, line 1)